<?php
class AlaxosJavascriptsController extends AppController
{
    function beforeFilter()
    {
        parent :: beforeFilter();
        
        $this->layout = null;
        
        if(isset($this->Auth))
        {
            $this->Auth->allow('ajax_security', 'antispam');
        }
        
        if($this->request->params['action'] == 'ajax_security')
        {
            if(!$this->Components->attached('Alaxos.AjaxSecurity'))
            {
                $this->AjaxSecurity = $this->Components->load('Alaxos.AjaxSecurity');
            }
        }
        elseif($this->request->params['action'] == 'antispam')
        {
            if(!$this->Components->attached('Alaxos.AlaxosSpamChecker'))
            {
                $this->AlaxosSpamChecker = $this->Components->load('Alaxos.AlaxosSpamChecker');
            }
        }
    }
    
    function ajax_security()
    {
        /*
         * The javascript returned by this method is meant to be used with the AjaxSecurityComponent
         *
         * When both are used, a new CSRF token generated by the AjaxSecurityComponent is returned
         * in a cookie in the HTTP response that returns the javascript code.
         *
         * This is the reason to make the JS code available through a controller.
         */
    }
    
    /**
     * Return a JS that will complete an HTML form with a hidden field that changes every day
     * 
     * @param string $form_dom_id The dom id of the form to secure
     * @param unknown_type $model_name The model name of the data
     */
    function antispam($form_dom_id, $model_name)
    {
        $today_fieldname = $this->AlaxosSpamChecker->get_today_fieldname();
        
        $this->set(compact('form_dom_id', 'model_name', 'today_fieldname'));
    }
}